config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users
  #, :skip => [:registrations]
  as :user do 
    get 'signin', to: 'devise/sessions#new'
    delete 'signout', to: 'devise/sessions#destroy'
    get 'signup', to: 'devise/registrations#new'
  end

  get 'feed', to: 'feed#show'
  
  resources :users, only: :show, param: :username do
    member do
      post 'follow', to: 'follows#create'
      delete 'unfollow', to: 'follows#destroy'
    end
  end
  
  resources :items do
    member do
      post 'vote', to: 'votes#create'
      delete 'unvote', to: 'votes#destroy'
    end
  end
  resources :tweets
  root "pages#home"
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_auth.rb
class AdminAuth < ActiveAdmin::AuthorizationAdapter

    def authorized?(action, subject = nil)
        user && user.admin?
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ApplicationRecord

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" and "follower" interface
  belongs_to :followable, polymorphic: true
  belongs_to :follower,   polymorphic: true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user

  validates :user, presence: true

  validate :url_or_text

  acts_as_votable
  
  private
    def url_or_text
      unless url.blank? ^ text.blank?
        errors.add(:base, "Specify a URL or text, not both.")
      end
    end

end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user

  validates :user, presence: true
  validates :content, presence: true, length: { maximum: 280 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :rememberable, :validatable
  
  has_many :tweets
  has_many :items

  validates :username, presence: true, uniqueness: true, length: { minimum: 3 }
  validates :name, presence: true

  acts_as_followable
  acts_as_follower
  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :configure_permitted_parameters, if: :devise_controller?
    
    def access_denied(exception)
        redirect_to root_path, alert: exception.message
    end

    protected
    
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name])
    end
end

app/controllers/feed_controller.rb
class FeedController < ApplicationController
    before_action :authenticate_user!

    def show
        @tweets = Tweet.where(user: current_user.all_following)
    end
  end
  

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
    before_action :authenticate_user!

    def create
        user = User.find_by(username: params[:username])
        Follow.create(followable: user, follower: current_user)
        redirect_to user_path(user.username), notice: "Successfully followed user"
    end
    
    def destroy
        user = User.find_by(username: params[:username])
        Follow.find_by(followable: user, follower: current_user).destroy
        redirect_to user_path(user.username), notice: "Successfully unfollowed user"
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:edit, :update, :destroy]

  # GET /items
  def index
    @items = Item.all
  end

  # GET /items/1
  def show
    @item = Item.find(params[:id])
  end

  # GET /items/new
  def new
    @item = current_user.items.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  def create
    @item = current_user.items.new(item_params)
    if @item.save
      redirect_to @item, notice: 'Item was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /items/1
  def update
    if @item.update(item_params)
      redirect_to @item, notice: 'Item was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /items/1
  def destroy
    @item.destroy
    redirect_to items_url, notice: 'Item was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = current_user.items.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :url, :text)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  def show
  end

  # GET /tweets/new
  def new
    @tweet = current_user.tweets.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  def create
    @tweet = current_user.tweets.new(tweet_params)

    if @tweet.save
      redirect_to @tweet, notice: 'Tweet was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tweets/1
  def update
    if @tweet.update(tweet_params)
      redirect_to @tweet, notice: 'Tweet was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tweets/1
  def destroy
    @tweet.destroy
    redirect_to tweets_url, notice: 'Tweet was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(username: params[:username])
    @tweets = @user.tweets
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
    before_action :authenticate_user!

    def create
        item = Item.find(params[:id])
        item.liked_by current_user
        redirect_to items_path, notice: "You successfully voted for an item"
    end
    
    def destroy
        item = Item.find(params[:id])
        item.unliked_by current_user
        redirect_to items_path, notice: "You successfully unvoted for an item"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/feed/show.html.erb
<div class="content">
  <div class="row">

    <div class="col-md-4">
        <% if user_signed_in? %>
        <div class="card" style="max-width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">Your Account</h5>
                <p class="card-text"><%= link_to current_user.username, user_path(current_user.username) %></p>
            </div>
            </div>
        <% end %>
    </div>
    <div class="col-md-8">

    <% if user_signed_in? %>
      <%= link_to 'New Tweet', new_tweet_path %>
    <% end %>

      <ul class="list-group">
        <% @tweets.each do |tweet| %>
          <%= link_to tweet, class: "list-group-item list-group-item-action flex-column align-items-start" do %>
            <h5 class="mb-1"><%= tweet.user.username %></h5>
            <p class="mb-1"><%= tweet.content %></p>
          <% end %>
        <% end %>
      </ul>

    </div>
  </div>
</div>

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :url %>
    <%= form.text_field :url, class: "form-control" %>
  </div>

  <p><strong>or</strong></p>
  
  <div class="form-group">
    <%= form.label :text %>
    <%= form.text_area :text, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/items/edit.html.erb
<div class="container">
    <h1>Editing Item</h1>

    <%= render 'form', item: @item %>

    <%= link_to 'Show', @item %> |
    <%= link_to 'Back', items_path %>
</div>

app/views/items/index.html.erb
<div class="container">

  <h1>Items</h1>

  <table>
    <thead>
      <tr>
        <th>Votes</th>
        <th>User</th>
        <th>Title</th>
        <th>Url</th>
        <th>Text</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= item.votes_for.up.size %></td>
          <td><%= item.user.username %></td>
          <td><%= item.title %></td>
          <td><%= item.url %></td>
          <td><%= item.text %></td>
          <% if user_signed_in? %>
            <% if current_user.voted_up_on? item %>
            <td><%= link_to 'Unvote', unvote_item_path(item), method: :delete %></td>
            <% else %>
            <td><%= link_to 'Vote', vote_item_path(item), method: :post %></td>
            <% end %>
          <% end %>
          <td><%= link_to 'Show', item %></td>
          <% if item.user == current_user %>
            <td><%= link_to 'Edit', edit_item_path(item) %></td>
            <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
          </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Item', new_item_path %>
</div>

app/views/items/new.html.erb
<div class="container">
    <h1>New Item</h1>

    <%= render 'form', item: @item %>

    <%= link_to 'Back', items_path %>
</div>

app/views/items/show.html.erb
<div class="container">

  <p>
    <strong>User:</strong>
    <%= @item.user.email %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= @item.title %>
  </p>

  <% if @item.url? %>
    <p>
      <strong>Url:</strong>
      <%= @item.url %>
    </p>
  <% end %>

  <% if @item.text? %>
    <p>
      <strong>Text:</strong>
      <%= @item.text %>
    </p>
  <% end %>

  <% if @item.user == current_user %>
    <%= link_to 'Edit', edit_item_path(@item) %>
  <% end %>
  <%= link_to 'Back', items_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>One Month Rails Project</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- Navigation Bar -->
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <div class="container">
        <%= link_to "One Month Rails", root_path, class: "navbar-brand" %>
        <ul class="navbar-nav flex-fill">
          <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "About", about_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Contact", contact_path, class: "nav-link" %></li>
        </ul>
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item"><%= link_to "Log out", signout_path, method: :delete, class: "nav-link" %></li>
          <% else %>
            <li class="nav-item"><%= link_to "Sign in", signin_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "Sign up", signup_path, class: "btn btn-primary" %></li>
          <% end %>
        </ul>
      </div>
    </nav>

    <!-- Flash messages -->
    <% flash.each do |name, message| %>
      <%= content_tag(:div, message, class: "alert alert-info #{name}") %>
    <% end %>

    <!-- Page Content -->
    <%= yield %>
    
    <!-- Footer -->
    <footer class="small text-muted">
      <div class="container">
        <hr>
        <center>
          <p>© 2019 One Month</p>
        </center>
      </div>
    </footer>

  </body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">
    <div class="container">
        <h1>About us</h1>
        <p>This is the sample project I built for <a href="https://onemonthrails.com">One Month Rails</a>.</p>
    </div>
</div>

app/views/pages/contact.html.erb
<h1>Contact us</h1>
<p>Info about how to contact us.</p>

app/views/pages/home.html.erb
<% if user_signed_in? %>
    <div class="jumbotron jumbotron-home">
        <div class="container">
        <h1>Welcome back!</h1>
        </div>
    </div>
<% else %>
    <div class="jumbotron jumbotron-home">
        <div class="container">
            <h1>Welcome to my website!</h1>
            <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
            <%= link_to "Learn more »", "#", class: "btn btn-primary btn-lg" %> 
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <h2>Heading</h2>
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
            </div>
            <div class="col-md-4">
                <h2>Heading</h2>
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
            </div>
            <div class="col-md-4">
                <h2>Heading</h2>
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
            </div>
        </div>
    </div>
<% end %>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<div class="container">
    <h1>Editing Tweet</h1>

    <%= render 'form', tweet: @tweet %>

    <%= link_to 'Show', @tweet %> |
    <%= link_to 'Back', tweets_path %>
</div>

app/views/tweets/index.html.erb
<div class="content">

  <div class="row">
    <div class="col-md-4">
      <div class="card" style="max-width: 18rem;">
        <div class="card-body">
          <% if user_signed_in? %>
            <h5 class="card-title">Your Account</h5>
            <p class="card-text"><%= link_to current_user.username, user_path(current_user.username) %></p>
          <% else %>
            <p class="card-text"><%= link_to "Sign up now!", signup_path %></p>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-8">

    <% if user_signed_in? %>
      <%= link_to 'New Tweet', new_tweet_path %>
    <% end %>

      <ul class="list-group">
        <% @tweets.each do |tweet| %>
          <%= link_to tweet, class: "list-group-item list-group-item-action flex-column align-items-start" do %>
            <h5 class="mb-1"><%= tweet.user.username %></h5>
            <p class="mb-1"><%= tweet.content %></p>
          <% end %>
        <% end %>
      </ul>

    </div>
  </div>
</div>

app/views/tweets/new.html.erb
<div class="container">
    <h1>New Tweet</h1>

    <%= render 'form', tweet: @tweet %>

    <%= link_to 'Back', tweets_path %>
</div>

app/views/tweets/show.html.erb
<div class="content">
  <div class="row">
    <div class="offset-md-2 col-md-8">

      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= link_to @tweet.user.username, user_path(@tweet.user.username) %></h5>
          <p class="card-text"><%= @tweet.content %></p>
          <% if @tweet.user == current_user %>
            <%= link_to 'Edit', edit_tweet_path(@tweet), class: "card-link" %>
            <%= link_to 'Delete', @tweet, method: :delete, class: "card-link" %>
          <% end %>
          <%= link_to 'Back', tweets_path, class: "card-link" %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="content">

  <div class="row">
    <div class="col-md-4">
    <% if user_signed_in? %>
      <div class="card" style="max-width: 18rem;">
          <div class="card-body">
            <h5 class="card-title"><%= @user.username %></h5>
            <p class="card-text"><%= @user.name %></p>
            <% if user_signed_in? %>
              <% if current_user.following?(@user) %>
                <p class="card-text"><%= link_to "Unfollow", unfollow_user_path(@user.username), method: :delete %></p>
              <% else %>
                <p class="card-text"><%= link_to "Follow", follow_user_path(@user.username), method: :post %></p>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-md-8">
      <ul class="list-group">
        <% @tweets.each do |tweet| %>
          <%= link_to tweet, class: "list-group-item list-group-item-action flex-column align-items-start" do %>
            <h5 class="mb-1"><%= tweet.user.username %></h5>
            <p class="mb-1"><%= tweet.content %></p>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</div>